### ISSUE TITLE
r_w register without fields does not yield a check function

### ISSUE THREAD

**Issue by LukasVik** [hdl-registers/hdl-registers#139]
**Description**
Problem in `VhdlSimulationCheckPackageGenerator`.

**How to reproduce?**

```toml
[config]

mode = "r_w"
```
